/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        grape: { DEFAULT: '#4A1F8C', deep: '#2E0F5C' },
        plum: '#7B36C7',
        lavender: { DEFAULT: '#EFD9FF', mid: '#E1BFFF' },
        cream: '#FFF6E8',
        pink: '#EC3B8E',
        orange: '#F37A2B',
        lemon: '#F5CF3E',
        mint: '#6CD7C2',
        ink: '#2A0F4F',
      },
      fontFamily: {
        display: ['"Bagel Fat One"', 'Caprasimo', 'serif'],
        groove: ['Caprasimo', 'serif'],
        body: ['"DM Sans"', 'system-ui', 'sans-serif'],
        hand: ['Caveat', 'cursive'],
      },
      boxShadow: {
        card: '6px 6px 0 #4A1F8C',
        'card-hover': '9px 9px 0 #4A1F8C',
        btn: '4px 4px 0 #4A1F8C',
        'btn-hover': '6px 6px 0 #4A1F8C',
        'btn-nav': '3px 3px 0 #EC3B8E',
        'btn-nav-hover': '5px 5px 0 #EC3B8E',
      },
      spacing: {
        '4.5': '18px',
        '5.5': '22px',
      },
      fontSize: {
        '2xs':  ['11px', { lineHeight: '1.4' }],
        'xs':   ['12px', { lineHeight: '1.4' }],
        'sm':   ['13px', { lineHeight: '1.35' }],
        'tag':  ['14px', { lineHeight: '1.4'  }],
        'body': ['15px', { lineHeight: '1.55' }],
        'md':   ['17px', { lineHeight: '1.55' }],
        'lg':   ['18px', { lineHeight: '1.5'  }],
        'xl':   ['22px', { lineHeight: '1.1'  }],
        '2xl':  ['26px', { lineHeight: '1.05' }],
        '3xl':  ['28px', { lineHeight: '1'    }],
        '4xl':  ['34px', { lineHeight: '1'    }],
        '5xl':  ['48px', { lineHeight: '.95'  }],
      },
      letterSpacing: {
        normal:  '.04em',
        meta:    '.1em',
        label:   '.16em',
        sub:     '.18em',
        eyebrow: '.22em',
        tag:     '.3em',
      },
      lineHeight: {
        heading: '.95',
        tight:   '1',
        snug:    '1.25',
        compact: '1.4',
        base:    '1.55',
      },
      borderRadius: {
        pill:      '9999px',
        circle:    '50%',
        'card-lg': '32px',
        card:      '24px',
        'card-sm': '20px',
        badge:     '16px',
        inner:     '14px',
        input:     '12px',
      },
      borderWidth: {
        fine:  '1.5px',
        base:  '2px',
        thick: '2.5px',
        rule:  '3px',
      },
    },
  },
  plugins: [],
};
